language: java

jdk: oraclejdk8

# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
    - ORG_GRADLE_PROJECT_ideaVersion="LATEST-EAP-SNAPSHOT" ORG_GRADLE_PROJECT_phpPluginVersion="LATEST"
    - ORG_GRADLE_PROJECT_ideaVersion="IU-2016.2" ORG_GRADLE_PROJECT_phpPluginVersion="162.1121.34"
    - ORG_GRADLE_PROJECT_ideaVersion="IU-2016.1" ORG_GRADLE_PROJECT_phpPluginVersion="145.970.40"
    - ORG_GRADLE_PROJECT_ideaVersion="IU-15.0.6" ORG_GRADLE_PROJECT_phpPluginVersion="143.1770"